import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Typewriter from 'typewriter-effect';
import BasicCard from '../components/BasicCard';
import { Box } from '@mui/system';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>
          Hello my name is,
        </h2>
        <h1 className={styles.title}>
          Carlos Rivera-Velázquez
        </h1>
        <h1 className={styles.typewriter}>
        <Typewriter
        options={{
          strings: ['Full Stack Developer', 'Web Developer', 'Mobile App Developer', 'Machine Learning Developer'],
          autoStart: true,
          loop: true,
          delay: 150,
          deleteSpeed: 100,
        }}
        />
        </h1>
      <Box mt={5}>
      <BasicCard 
        content={"I'm a software engineer with 3+ years of experience in the software industry. Mainly focused on full-stack web development with NextJS and mobile development with React Native. My experience also includes the development of machine learning algorithms mostly involving computer vision and natural language processing."}
      />
      </Box>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
