import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Typewriter from 'typewriter-effect';
import BasicCard from '../components/BasicCard';
import { Box } from '@mui/system';
import LinkedInIcon from '@mui/icons-material/LinkedIn';
import { Typography, Grid, Button } from '@mui/material';
import GitHubIcon from '@mui/icons-material/GitHub';
import Timeline from '../components/Timeline';
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Button onClick={() => router.push('/snake')}>button</Button>
        <h2>
          Hello my name is,
        </h2>
        <h1 className={styles.title}>
          Carlos Rivera-Velázquez
        </h1>
        <h1 className={styles.typewriter}>
        <Typewriter
        options={{
          strings: ['Full Stack Developer', 'Web Developer', 'Mobile App Developer', 'Machine Learning Developer'],
          autoStart: true,
          loop: true,
          delay: 150,
          deleteSpeed: 100,
        }}
        />
        </h1>
      <Box mt={5}>
        <BasicCard 
          content={"I'm a software engineer with 3+ years of experience in the software industry. Mainly focused on full-stack web development with NextJS and mobile development with React Native. My experience also includes the development of machine learning algorithms, mostly involving computer vision and natural language processing."}
        />
      </Box>
      <Box mt={5}>
      <h1>
        <i>Experience</i>
      </h1>
      </Box>
      <Timeline/>
      <Box mt={10}>
        <Grid container spacing={10}>
          <Grid item xs={6}>
            <a href={'https://www.linkedin.com/in/carlos-rivera-velazquez/'} target="_blank">
              <Grid container spacing={1}>
                <Grid item xs={4}>
                  <LinkedInIcon fontSize='large'/>
                </Grid>
                <Grid item xs={8}>
                  <Typography sx={{ fontSize: 12 }} gutterBottom>
                    <b>LinkedIn Profile</b>
                  </Typography>
                </Grid>
              </Grid>
            </a>
          </Grid>
          <Grid item xs={6}>
            <a href={'https://github.com/carlosrivera22'} target="_blank">
              <Grid container spacing={2}>
                <Grid item xs={4}>
                  <GitHubIcon fontSize='large'/>
                </Grid>
                <Grid item xs={8}>
                  <Typography sx={{ fontSize: 12 }} gutterBottom>
                    <b>Github <br/> Profile</b>
                  </Typography>
                </Grid>
              </Grid>
            </a>
          </Grid>
        </Grid>
      </Box>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
